source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PagedHorizontalView_Example', :exclusive => true do
  pod "PagedHorizontalView", :path => "../"
end

target 'PagedHorizontalView_Tests', :exclusive => true do
  pod "PagedHorizontalView", :path => "../"

  
end
